# Generated by Django 3.0.3 on 2020-06-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('hotelname', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=1)),
                ('ambience', models.CharField(max_length=1)),
                ('hospitality', models.CharField(max_length=1)),
                ('rating', models.CharField(max_length=1)),
                ('review', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('about', models.CharField(max_length=250)),
                ('logo', models.URLField()),
                ('image', models.URLField()),
                ('numberSeats', models.CharField(max_length=5)),
                ('hotelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=10)),
                ('numberPeople', models.IntegerField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1app.Client')),
            ],
        ),
    ]
