# Generated by Django 3.0.3 on 2020-06-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0005_auto_20200618_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hotelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1app.Owner'),
        ),
    ]
