# Generated by Django 3.0.3 on 2020-06-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0006_auto_20200618_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hotelname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project1app.Owner'),
            preserve_default=False,
        ),
    ]
