# Generated by Django 3.0.3 on 2020-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0008_review_hotelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.CharField(max_length=50),
        ),
    ]
