# Generated by Django 3.0.3 on 2020-06-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0009_auto_20200620_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
