# Generated by Django 3.0.3 on 2020-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0014_auto_20200620_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(max_length=255, upload_to='project1app/media'),
        ),
    ]
