# Generated by Django 3.0.3 on 2020-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0015_auto_20200620_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(max_length=255, upload_to='project1app/media'),
        ),
    ]
