# Generated by Django 3.0.3 on 2020-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0017_auto_20200620_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
