# Generated by Django 3.0.3 on 2020-06-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0018_auto_20200621_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
