# Generated by Django 3.0.3 on 2020-06-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0019_auto_20200621_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='numberSeats',
            field=models.IntegerField(),
        ),
    ]
